### ISSUE TITLE
localFile should be removed and core/File extended to fit your needs

### ISSUE THREAD

**Issue by lzehl** [HumanBrainProject/openMINDS_computation#21]
I strongly suggest to remove the concept of a "localFile" vs a "File" if the IRI is the only problem. This can be solved differently by adapting just using the "File" schema in core with a local file path IRI pattern (e.g., "file://"+ (host)/ + (local path))

**Comment by apdavison** [comment]
I had a long discussion about this with Oli (I thought you were also involved, but perhaps not), and LocalFile was Oli's preferred solution. I don't remember the reasons now, and the message thread has disappeared into the "pay-to-view" part of Slack, but I think the main reason for having separate concepts was all the automation put in place by the KG team around Files. 

Very often LocalFiles do not exist anymore, they're just needed to show that the file once existed (in a provenance context), and to provide a content hash so that if the same workflow is run again we can check if the new file contents match those from the last time the workflow was run.

**Comment by lzehl** [comment]
@apdavison okay. Then we keep it. I couldn't remember if we discussed this or not.
